### ISSUE TITLE
Add remote location to a mod

### ISSUE THREAD

**Issue by ghost** [mcrocks999/solder.js#3]
Some mod authors do not allow rehosting of their mods (For example [JourneyMap](http://journeymap.info/Modpack_FAQ))

Of course, making this a thing would also require some MD5 trickery (probably caching the mods on the Solder.js side) to make it work (I think)

**Comment by mcrocks999** [comment]
Obvious issue here is that remote files would not be in the correct structure for Technic.
e.g. no zip files with the jar being in the mods folder in said zip

**Comment by ghost** [comment]
Actually certain mods are in the certain structure (For example [JourneyMap again](https://minecraft.curseforge.com/projects/journeymap/files/2492368/download))

Also if the mods are in Jar form, they can easily be packed using node-zip.

**Comment by mcrocks999** [comment]
Ok.
Regarding the repack idea, that breaks the idea that we cannot **rehost** them.

**Comment by ghost** [comment]
True, packing would mean that the file **has** to be accessed from a URL, but often times authors do not want rehosting because they want to see numbers. Downloading the mod then packing it *may* not really matter that much then.

**Comment by mcrocks999** [comment]
I don't think it would be a smart idea to have to download and repack every single time someone downloads, and if we avoid that then the author dosen't get those "statistics".
