### ISSUE TITLE
Donate field is required apparently.

### ISSUE THREAD

**Issue by mcrocks999** [mcrocks999/solder.js#4]
@FatalErrorCode determined that not having the donate field can cause errors.

**Comment by mcrocks999** [comment]
haha I failed, see commit: 77392e570680d3b9f9e6bef07063422efda2b8c2

**Comment by ghost** [comment]
I actually realized that **all** the fields are required at all costs, for every request (obviously some need to be actually filled with something like the build `minecraft` field and the mod `name` and `pretty_name` fields)
